### ISSUE TITLE
v2: hangs when using extrudeRotate, polygon and union

### ISSUE THREAD

**Issue by crysislinux** [jscad/OpenJSCAD.org#719]
I have a minimal code to reproduce the issue.

```js
const { primitives, booleans, extrusions } = require('@jscad/modeling');
const { union } = booleans;
const { extrudeRotate } = extrusions;
const { polygon, cylinder } = primitives;

module.exports.main = () => {
  const points = [
    [0, 0],
    [10, 0],
    [10, 5],
    [0, 5]
  ]

  const p = extrudeRotate({}, polygon({ points }));
  const c = cylinder({radius: 2, height: 20} );

  // return [p, c];
  return union(p, c)
}
```

without the union(return them in an array), it renders like this:

![image](https://user-images.githubusercontent.com/5404597/96588972-dc3b1580-1316-11eb-8f19-b97042ac4daf.png)

## Expected Behavior
It should render properly (looks the same as the version without union)

## Actual Behavior
It hanges forever and cpu usage is high.

The issue actually happens for all boolean operation on the object returns from extrudeRotate

## Steps to Reproduce the Problem

  1. download the reproduce file 
[reproduce.js.zip](https://github.com/jscad/OpenJSCAD.org/files/5408797/reproduce.js.zip)

  2. unzip it and drag it into v2 website: https://www.jscad.xyz/
  3. you will see that it doesn't render.
  4. replace `return union(p, c)` with `return [p, c]`, it renders properly.

## Specifications

  - Version: v2
  - Platform: mac
  - Environment:  browser Chrome Version 86.0.4240.80

**Comment by z3dev** [comment]
@crysislinux nice example. it's probably an issue with the generated polygons, probably the caps on top and bottom.

**Comment by gilboonet** [comment]
I replaced the extrudeRotate with a cylinder and then the union renders without hanging, there is certainly an issue, but with extrudeRotate + union. I exported both volumes to Meshlab and they were exactly the same.
![Capture d’écran de 2020-10-21 11-21-07](https://user-images.githubusercontent.com/22082873/96700445-bd2c9a00-138f-11eb-867f-db469aee2bac.png)

**Comment by crysislinux** [comment]
@gilboonet yeah, cylinder works in the example. But it's just for demonstration. In reality, we need `extrudeRotate` very much to create special shapes.

**Comment by gilboonet** [comment]
@crysislinux I understand and I use extrudeRotate too on some designs. My point was to say that the problem is complex, the volume created by extrudeRotate there is exactly the same as a cylinder and therefore its union with a cylinder hangs when union of two cylinders render ok. Must test with another shape than a cylinder, to see if it is due to extrudeRotate or union of different kinds of shape that hangs.

**Comment by crysislinux** [comment]
@gilboonet 

the example was simplified by purpose. I tried different kinds of shapes, it hangs if there is a shape(no only a cylinder) created with `extrudeRotate` when doing boolean operations.

**Comment by z3dev** [comment]
Definitely an issue with the top / bottom polygons as there are duplicated polygons. Here's the polygons from the top.
```
{"vertices":[[10,-3.061616997868383e-16,-5],[0,-3.061616997868383e-16,-5],[2.1648901405887328e-16,-2.1648901405887336e-16,-5]]},
{"vertices":[[10,-3.061616997868383e-16,-5],[2.1648901405887328e-16,-2.1648901405887336e-16,-5],[7.0710678118654755,7.071067811865475,-5]]},
{"vertices":[[7.0710678118654755,7.071067811865475,-5],[2.1648901405887328e-16,-2.1648901405887336e-16,-5],[3.061616997868383e-16,-1.874699728327322e-32,-5]]},
{"vertices":[[7.0710678118654755,7.071067811865475,-5],[3.061616997868383e-16,-1.874699728327322e-32,-5],[9.18485099360515e-16,10,-5]]},
{"vertices":[[9.18485099360515e-16,10,-5],[3.061616997868383e-16,-1.874699728327322e-32,-5],[2.1648901405887336e-16,2.1648901405887328e-16,-5]]},
{"vertices":[[9.18485099360515e-16,10,-5],[2.1648901405887336e-16,2.1648901405887328e-16,-5],[-7.071067811865475,7.0710678118654755,-5]]},
{"vertices":[[-7.071067811865475,7.0710678118654755,-5],[2.1648901405887336e-16,2.1648901405887328e-16,-5],[3.749399456654644e-32,3.061616997868383e-16,-5]]},
{"vertices":[[-7.071067811865475,7.0710678118654755,-5],[3.749399456654644e-32,3.061616997868383e-16,-5],[-10,1.5308084989341915e-15,-5]]},
{"vertices":[[-2.1648901405887336e-16,-2.1648901405887328e-16,5],[-7.071067811865475,7.0710678118654755,5],[-10,9.18485099360515e-16,5]]},
{"vertices":[[-2.1648901405887336e-16,-2.1648901405887328e-16,5],[-10,9.18485099360515e-16,5],[-3.749399456654644e-32,-3.061616997868383e-16,5]]},
{"vertices":[[-10,1.5308084989341915e-15,-5],[3.749399456654644e-32,3.061616997868383e-16,-5],[-2.1648901405887328e-16,2.1648901405887338e-16,-5]]},
{"vertices":[[-10,1.5308084989341915e-15,-5],[-2.1648901405887328e-16,2.1648901405887338e-16,-5],[-7.071067811865477,-7.071067811865475,-5]]},
{"vertices":[[-7.071067811865477,-7.071067811865475,-5],[-2.1648901405887328e-16,2.1648901405887338e-16,-5],[-3.061616997868383e-16,5.624099184981967e-32,-5]]},
{"vertices":[[-7.071067811865477,-7.071067811865475,-5],[-3.061616997868383e-16,5.624099184981967e-32,-5],[-2.143131898507868e-15,-10,-5]]},
{"vertices":[[-2.143131898507868e-15,-10,-5],[-3.061616997868383e-16,5.624099184981967e-32,-5],[-2.1648901405887338e-16,-2.1648901405887328e-16,-5]]},
{"vertices":[[-2.143131898507868e-15,-10,-5],[-2.1648901405887338e-16,-2.1648901405887328e-16,-5],[7.071067811865475,-7.071067811865477,-5]]},
{"vertices":[[7.071067811865475,-7.071067811865477,-5],[-2.1648901405887338e-16,-2.1648901405887328e-16,-5],[-7.498798913309288e-32,-3.061616997868383e-16,-5]]},
{"vertices":[[7.071067811865475,-7.071067811865477,-5],[-7.498798913309288e-32,-3.061616997868383e-16,-5],[10,-2.7554552980815448e-15,-5]]},
```
Now that I know the issue, a fix is probably possible.

**Comment by z3dev** [comment]
UG... Here's what's happening.

In the normal case, the 'walls' between previous and current slices are created as 'triangles'. All fine when the slices have unique edges (no overlap).

But in this special case, the slices actually have overlapping edges. This makes 'trangles' that also overlap.

And of course, those boolean functions will die a horible death.

**Comment by z3dev** [comment]
I recognized this issue when revisting rotate extrude in V2. The comment says... in the overlapping case...
```
  // FIXME actually there are cases where setting X=0 will change the basic shape
  // - Alternative #1 : don't allow shapes with both negative and positive X values
  // - Alternative #2 : remove one half of the shape (costly)
```
It's even worse than I thought.

**Comment by crysislinux** [comment]
@z3dev is there a workaround to the issue?

I find myself really need this bc I don't know other ways to create an unusual shape.

**Comment by z3dev** [comment]
For now, make sure the 2D shape has X > 0. It can be a very small X.

**Comment by z3dev** [comment]
> I find myself really need this bc I don't know other ways to create an unusual shape.

@crysislinux can you provide a short example?

**Comment by crysislinux** [comment]
@z3dev 

I am building things like this one:

![image](https://user-images.githubusercontent.com/5404597/97097698-aac3a080-16ae-11eb-972a-a3e1bb514ce9.png)

The practical way I can think of is creating a 2d shape and then `extrudeRotate` it to a 3d object.

**Comment by z3dev** [comment]
@crysislinux there's a new pull request for the fixes. here's the result from the original example.

![6](https://user-images.githubusercontent.com/8969165/97772075-ca633900-1b86-11eb-8138-f69024409e95.png)

I tested several different variations of 2D shapes that start from X=0, as well as shapes that overlap the X axis (-/+). And actually discovered another issue. 🐛  

You'll see these fixes in the next ALPHA release, sometime next week. Or you can pull the branch with the fix and use locally.

And thanks all for the great discussion and examples. Those small tidbits of information excellerate the development.

**Comment by crysislinux** [comment]
@z3dev wow, that's nice. Thanks.

**Comment by z3dev** [comment]
@crysislinux @gilboonet @BarbourSmith did you get a change to try the latest release? this should be fixed now.

**Comment by crysislinux** [comment]
@z3dev haven't got time yet. I will try it at the weekend, thanks.

**Comment by BarbourSmith** [comment]
The issue with the render hanging seems to be fixed for me 👍 

Unfortunately I am still seeing some artifacts although they may be caused by something else unrelated to this issue.

From doing some reading it seems that the underlying math may be to blame. My understanding is that doing successive boolean operations using floating point math will always eventually lead to artifacts and non-manifold geometry. Does anyone have any thoughts about that limitation?

**Comment by z3dev** [comment]
See the discussion on Issue #696 
I'm working on some changes now to snap, to triangulate, and to manifold 3D geometries.

**Comment by BarbourSmith** [comment]
Ahh right, my bad. I think I confused these two issues. Very cool!

I tested a good number of shapes without getting the renderer to hang so from my perspective this one looks fixed.

**Comment by z3dev** [comment]
Let’s close this issue, and open a new issue if anything shows up.
